# Generated by Django 4.2.26 on 2025-11-25 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_type',
            field=models.CharField(default='Account Notifications', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='No message here!'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
