# Generated by Django 4.2.26 on 2025-11-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pricechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='prep_time',
            field=models.IntegerField(default=0, help_text='Preparation time in minutes'),
        ),
    ]
